"""
Step 8: Measure data quality and record the results.

Runs every check in dq_rules.py against the loaded database, then stores:
  dq_runs        one row for this run
  dq_results     the scorecard: one row per check
  dq_exceptions  the review queue: one row per flagged record
and writes a readable copy of the scorecard to reports/dq_scorecard.md.

Exits with code 1 if any critical check fails, so a scheduler can stop
downstream work on bad data. Warnings never fail the run; they are queued
for review.

Run after 05:  python scripts/08_run_data_quality.py
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from utils import setup_logging, get_connection, PROJECT_ROOT as _ROOT
from dq_rules import CheckResult, run_all_checks

logger = setup_logging(__name__)
PROJECT_ROOT = Path(_ROOT)
DQ_SCHEMA_PATH = PROJECT_ROOT / "sql" / "dq_schema.sql"
REPORT_PATH = PROJECT_ROOT / "reports" / "dq_scorecard.md"

SAMPLES_PER_CHECK = 5   # flagged records shown per check in the report


def save_run(conn, results: list[CheckResult], run_at: str, data_source: str) -> int:
    """Write the run, its scorecard and its exceptions. Returns the run_id."""
    statuses = [r.status for r in results]
    cursor = conn.execute(
        "INSERT INTO dq_runs (run_at, data_source, checks_run, checks_passed, "
        "checks_warned, checks_failed) VALUES (?, ?, ?, ?, ?, ?)",
        (run_at, data_source, len(results), statuses.count("PASS"),
         statuses.count("WARN"), statuses.count("FAIL")))
    run_id = cursor.lastrowid

    for r in results:
        conn.execute(
            "INSERT INTO dq_results VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (run_id, r.check_id, r.table_name, r.dimension, r.severity,
             r.description, r.rows_checked, r.rows_failed, r.pass_rate,
             r.threshold, r.status))
        conn.executemany(
            "INSERT INTO dq_exceptions VALUES (?, ?, ?, ?)",
            [(run_id, r.check_id, str(key), str(value))
             for key, value in zip(r.exceptions["record_key"], r.exceptions["value"])])
    return run_id


def build_report(results: list[CheckResult], run_id: int, run_at: str,
                 data_source: str) -> str:
    """The scorecard as Markdown: summary, by dimension, every check, samples."""
    statuses = [r.status for r in results]
    n_warn = statuses.count("WARN")
    lines = [
        "# Data quality scorecard",
        "",
        f"Run {run_id} · {run_at} · data source: **{data_source}** · "
        f"generated by `scripts/08_run_data_quality.py`",
        "",
        f"**{statuses.count('PASS')} passed · {n_warn} warning{'' if n_warn == 1 else 's'} · "
        f"{statuses.count('FAIL')} failed** out of {len(results)} checks.",
        "",
        "## By dimension",
        "",
        "| Dimension | Checks | Average pass rate | Not passing |",
        "|---|---:|---:|---:|",
    ]
    by_dimension = pd.DataFrame({
        "dimension": [r.dimension for r in results],
        "pass_rate": [r.pass_rate for r in results],
        "passing": [r.status == "PASS" for r in results],
    }).groupby("dimension", sort=False)
    for dimension, group in by_dimension:
        lines.append(f"| {dimension} | {len(group)} | {group.pass_rate.mean():.2%} "
                     f"| {int((~group.passing).sum())} |")

    lines += [
        "",
        "## Every check",
        "",
        "| Status | Check | What it tests | Rows checked | Flagged | Pass rate | Threshold |",
        "|---|---|---|---:|---:|---:|---:|",
    ]
    for r in results:
        lines.append(f"| {r.status} | `{r.check_id}` | {r.description} | {r.rows_checked:,} "
                     f"| {r.rows_failed:,} | {r.pass_rate:.2%} | {r.threshold:.1%} |")

    flagged = [r for r in results if r.rows_failed]
    if flagged:
        lines += ["", "## Flagged for review (samples)", ""]
        for r in flagged:
            lines.append(f"**`{r.check_id}`** ({r.rows_failed:,} flagged)")
            lines.append("")
            for key, value in zip(r.exceptions["record_key"][:SAMPLES_PER_CHECK],
                                  r.exceptions["value"][:SAMPLES_PER_CHECK]):
                lines.append(f"- `{key}`: {value}")
            lines.append("")
        lines.append("Full lists: `dq_exceptions` table; see `sql/dq_queries.sql`.")
    return "\n".join(lines) + "\n"


def main() -> None:
    conn = get_connection()
    conn.executescript(DQ_SCHEMA_PATH.read_text())   # CREATE IF NOT EXISTS: keeps history

    source_row = conn.execute(
        "SELECT value FROM pipeline_meta WHERE key = 'data_source'").fetchone()
    data_source = source_row[0] if source_row else "unknown"
    run_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    results = run_all_checks(conn)
    for r in results:
        log = logger.info if r.status == "PASS" else logger.warning
        log("%-4s %-32s %8s / %-8s pass %7.2f%%  (threshold %.1f%%)",
            r.status, r.check_id, f"{r.rows_failed:,}", f"{r.rows_checked:,}",
            100 * r.pass_rate, 100 * r.threshold)

    try:
        run_id = save_run(conn, results, run_at, data_source)
        conn.commit()                          # the whole run lands, or none of it
    except Exception:
        conn.rollback()
        logger.error("could not save DQ results; rolled back")
        raise
    finally:
        conn.close()

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(results, run_id, run_at, data_source))
    logger.info("run %d saved; scorecard written to %s", run_id,
                REPORT_PATH.relative_to(PROJECT_ROOT))

    failed = [r.check_id for r in results if r.status == "FAIL"]
    if failed:
        logger.error("critical checks failed: %s", ", ".join(failed))
        sys.exit(1)


if __name__ == "__main__":
    main()
